folio-org/ui-requests-mediated

.github/workflows/build-npm-release.yml, .github/workflows/build-npm.yml, CHANGELOG.md
Update github actions
Use the same github actions that use in check in, check out, request and etc instead of initial that was created after created   module with stripes-cli.
Associated with https://github.com/folio-org/platform-complete/pull/2597
https://issues.folio.org/browse/UIREQMED-14
=> UIREQMED-14: Update github actions

CHANGELOG.md, package.json
Hide permission that should not be visible
https://issues.folio.org/browse/UIREQMED-20
=> UIREQMED-20: Hide permission that should not be visible

CHANGELOG.md, package.json, translations/ui-requests-mediated/en.json
Update permission for Mediated requests
https://issues.folio.org/browse/UIREQMED-29
=> UIREQMED-29: Update permission for Mediated requests

CHANGELOG.md, src/components/MediatedRequestsActivities/MediatedRequestsActivities.js, src/components/MediatedRequestsActivities/MediatedRequestsActivities.test.js, src/components/MediatedRequestsActivities/components/MediatedRequestsList/MediatedRequestsList.js, src/components/MediatedRequestsActivities/components/MediatedRequestsList/MediatedRequestsList.test.js, src/constants/base.js, src/constants/mediatedRequestsActivities.js, test/jest/__mock__/stripesCore.mock.js, translations/ui-requests-mediated/en.json
* Add Actions button and dropdown in Mediated requests UI
https://issues.folio.org/browse/UIREQMED-6
=> UIREQMED-6: Add Actions button and dropdown in Mediated requests UI

CHANGELOG.md, src/constants/mediatedRequestsActivities.js, translations/ui-requests-mediated/en.json
* Add Closed - Cancelled status to Mediated request status filter
https://issues.folio.org/browse/UIREQMED-33
=> UIREQMED-33: Add Closed - Cancelled status to Mediated request status filter

CHANGELOG.md, src/components/MediatedRequestsActivities/MediatedRequestsActivities.js, src/components/MediatedRequestsActivities/MediatedRequestsActivities.test.js
Implement functionality of `New mediated request` button
[UIREQMED-35](https://folio-org.atlassian.net/browse/UIREQMED-35)
=> UIREQMED-35: Implement functionality of `New mediated request` button

package.json, src/utils.js, src/utils.test.js
Follow up PR
[UIREQMED-10](https://folio-org.atlassian.net/browse/UIREQMED-10)
=> UIREQMED-10: Mediated requests details content (FOLLOW_UP)

src/components/MediatedRequestsActivities/components/MediatedRequestInformation/MediatedRequestInformation.js, src/components/MediatedRequestsActivities/components/MediatedRequestInformation/MediatedRequestInformation.test.js, translations/ui-requests-mediated/en.json
Follow up PR of Implementation of Mediated requests details content
[UIREQMED-10](https://folio-org.atlassian.net/browse/UIREQMED-10)
=> UIREQMED-10: Implementation of Mediated requests details content (FOLLOW UP)

CHANGELOG.md, src/components/MediatedRequestsActivities/components/MediatedRequestsDetail/MediatedRequestsDetail.js, src/components/MediatedRequestsActivities/components/MediatedRequestsDetail/MediatedRequestsDetail.test.js, test/jest/__mock__/stripesCore.mock.js
Add instance title to page title if the detail record is opened.
[UIREQMED-16](https://folio-org.atlassian.net/browse/UIREQMED-16)
=> UIREQMED-16: Add instance title to page title if the detail record is opened

CHANGELOG.md, package.json, src/components/ConfirmItem/ConfirmItem.js, src/components/ConfirmItem/ConfirmItem.test.js, src/components/ConfirmItem/components/ConfirmItemList.js, src/components/ConfirmItem/components/ConfirmItemList.test.js, src/components/ConfirmItem/components/index.js, src/components/ConfirmItem/index.js, src/components/ConfirmItemArrival/ConfirmItemArrival.js, src/components/ConfirmItemArrival/ConfirmItemArrival.test.js, src/components/ErrorModal/ErrorModal.js, src/components/ErrorModal/ErrorModal.test.js, src/components/ErrorModal/index.js, src/components/MediatedRequestsActivities/MediatedRequestsActivities.js, src/components/MediatedRequestsActivities/MediatedRequestsActivities.test.js, src/components/NavigationMenu/NavigationMenu.js, src/components/NavigationMenu/NavigationMenu.test.js, src/components/SendItemInTransit/SendItemInTransit.js, src/components/SendItemInTransit/SendItemInTransit.test.js, src/constants/confirmItem.js, src/constants/index.js, test/jest/__mock__/stripesCore.mock.js, translations/ui-requests-mediated/en.json
Add Content for Confirm item arrival
https://issues.folio.org/browse/UIREQMED-8
=> UIREQMED-8: Add Content for Confirm item arrival

.github/workflows/build-npm-release.yml, .github/workflows/build-npm.yml, CHANGELOG.md
Update upload-artifact actions from v1 and v2 to v4
https://issues.folio.org/browse/UIREQMED-43
=> UIREQMED-43: Update upload-artifact actions from v1 and v2 to v4

CHANGELOG.md, src/components/MediatedRequestsActivities/MediatedRequestsActivities.js, src/components/MediatedRequestsActivities/MediatedRequestsActivities.test.js, translations/ui-requests-mediated/en.json
Update HTML page title when search term entered in search box.
[UIREQMED-17](https://folio-org.atlassian.net/browse/UIREQMED-17)
=> UIREQMED-17: Update HTML page title with search term entered

CHANGELOG.md, package.json, src/components/ConfirmItemArrival/ConfirmItemArrival.js, src/components/SendItemInTransit/SendItemInTransit.js, src/utils.js, src/utils.test.js
Add Content for Send item in transit
https://issues.folio.org/browse/UIREQMED-9
=> UIREQMED-9: Add Content for Send item in transit

src/components/MediatedRequestsActivities/MediatedRequestsActivities.js, src/components/MediatedRequestsActivities/MediatedRequestsActivities.test.js, src/index.js
FOLLOW UP PR related to Updating HTML page title with search term entered
=> UIREQMED-17: Update HTML page title with search term entered (FOLLOW-UP)

CHANGELOG.md, src/components/MediatedRequestsActivities/MediatedRequestsActivities.js
Persist filters when changing between actions
https://issues.folio.org/browse/UIREQMED-44
=> UIREQMED-44: Persist filters when changing between actions

CHANGELOG.md, package.json
Add circulation-storage.staff-slips.collection.get for get staff-slips on Send item in transit
https://issues.folio.org/browse/UIREQMED-55
=> UIREQMED-55: Add circulation-storage.staff-slips.collection.get for get staff-slips on Send item in transit

CHANGELOG.md, package.json, src/components/MediatedRequestsActivities/components/MediatedRequestsDetail/MediatedRequestsDetail.js, src/components/MediatedRequestsActivities/components/MediatedRequestsDetail/MediatedRequestsDetail.test.js, src/components/MediatedRequestsActivities/components/MediatedRequestsDetail/components/DeclineModal/DeclineModal.js, src/components/MediatedRequestsActivities/components/MediatedRequestsDetail/components/DeclineModal/DeclineModal.test.js, src/components/MediatedRequestsActivities/components/MediatedRequestsDetail/components/DeclineModal/index.js, src/hooks/useMediatedRequestById/useMediatedRequestById.js, src/routes/MediatedRequestsActivitiesContainer.js, src/routes/MediatedRequestsActivitiesContainer.test.js, src/utils.js, src/utils.test.js, translations/ui-requests-mediated/en.json
Add Decline Action for Mediated request with status of New - Awaiting confirmation
https://issues.folio.org/browse/UIREQMED-42
=> UIREQMED-42: Add Decline Action for Mediated request with status of New - Awaiting confirmation

CHANGELOG.md, src/components/SendItemInTransit/components/ContentToPrint.js
Fix DOMPurify import
https://issues.folio.org/browse/UIREQMED-56
=> UIREQMED-56: Fix DOMPurify import

CHANGELOG.md, package.json
Update permission after mod-requests-mediated permission changes
https://issues.folio.org/browse/UIREQMED-62
=> UIREQMED-62: Update permission after mod-requests-mediated permission changes

CHANGELOG.md
Release v2.0.0
https://issues.folio.org/browse/UIREQMED-54
=> Update changelog after Release v2.0.0

CHANGELOG.md
Update changelog after release
[UIREQMED-67](https://folio-org.atlassian.net/browse/UIREQMED-67)
=> UIREQMED-67: Update changelog after release

CHANGELOG.md, src/components/MediatedRequestsActivities/components/RequestForm/RequestForm.test.js, test/jest/__mock__/stripesComponents.mock.js
Increase code coverage of RequestForm.js
[UIREQMED-69](https://folio-org.atlassian.net/browse/UIREQMED-69)
=> UIREQMED-69: Increase code coverage of RequestForm.js

CHANGELOG.md
Update changelog after release
[UIREQMED-90](https://folio-org.atlassian.net/browse/UIREQMED-90)
=> UIREQMED-90: Update changelog after release

CHANGELOG.md, package.json
*BREAKING* Update react-intl to ^7
https://folio-org.atlassian.net/browse/UIREQMED-89
=> UIREQMED-89: *BREAKING* Update react-intl to ^7

CHANGELOG.md, package.json
*BREAKING* Update stripes-* dependencies to latest version
https://folio-org.atlassian.net/browse/UIREQMED-88
=> UIREQMED-88: *BREAKING* Update stripes-* dependencies to latest version

CHANGELOG.md
Update changelog after release
[UIREQMED-98](https://folio-org.atlassian.net/browse/UIREQMED-98)
=> UIREQMED-98: Update changelog after release

CHANGELOG.md, package.json, src/components/MediatedRequestsActivities/components/RequestFormContainer/RequestFormContainer.js, test/jest/__mock__/stripesComponents.mock.js
Replace moment with day.js
[UIREQMED-96](https://folio-org.atlassian.net/browse/UIREQMED-96)
=> UIREQMED-96: Replace moment with day.js

CHANGELOG.md, src/components/ConfirmItem/ConfirmItem.js, src/components/ConfirmItem/components/ConfirmItemList.js, src/components/MediatedRequestsActivities/MediatedRequestsActivities.js, src/components/MediatedRequestsActivities/components/FulfilmentPreference/FulfilmentPreference.js, src/components/MediatedRequestsActivities/components/InstanceInformation/InstanceInformation.js, src/components/MediatedRequestsActivities/components/ItemDetail/ItemDetail.js, src/components/MediatedRequestsActivities/components/ItemInformation/ItemInformation.js, src/components/MediatedRequestsActivities/components/MediatedRequestInformation/MediatedRequestInformation.js, src/components/MediatedRequestsActivities/components/MediatedRequestsDetail/MediatedRequestsDetail.js, src/components/MediatedRequestsActivities/components/MediatedRequestsFilters/MediatedRequestsFilters.js, src/components/MediatedRequestsActivities/components/MediatedRequestsList/MediatedRequestsList.js, src/components/MediatedRequestsActivities/components/PickupServicePoint/PickupServicePoint.js, src/components/MediatedRequestsActivities/components/RequestForm/RequestForm.js, src/components/MediatedRequestsActivities/components/RequestFormContainer/RequestFormContainer.js, src/components/MediatedRequestsActivities/components/RequestInformation/RequestInformation.js, src/components/MediatedRequestsActivities/components/RequesterInformation/RequesterInformation.js, src/components/MediatedRequestsActivities/components/UserDetail/UserDetail.js, src/components/MediatedRequestsActivities/components/UserForm/UserForm.js, src/components/SendItemInTransit/components/ContentToPrint.js, src/constants/confirmItem.js, src/index.js, src/routes/MediatedRequestsActivitiesContainer.js, src/routes/NoteCreator/NoteCreator.js, src/routes/NoteEditor/NoteEditor.js, src/routes/NoteViewer/NoteViewer.js
Reduce count of eslint errors after update eslint-config-stripes
https://issues.folio.org/browse/UIREQMED-95
=> UIREQMED-95: Reduce count of eslint errors after update eslint-config-stripes

src/components/MediatedRequestsActivities/MediatedRequestsActivities.js, src/components/MediatedRequestsActivities/components/InstanceInformation/InstanceInformation.js, src/components/MediatedRequestsActivities/components/ItemInformation/ItemInformation.js, src/components/MediatedRequestsActivities/components/MediatedRequestsDetail/MediatedRequestsDetail.js, src/components/MediatedRequestsActivities/components/MediatedRequestsFilters/MediatedRequestsFilters.js, src/components/MediatedRequestsActivities/components/MediatedRequestsList/MediatedRequestsList.js, src/components/MediatedRequestsActivities/components/RequestForm/RequestForm.js, src/components/MediatedRequestsActivities/components/RequestFormContainer/RequestFormContainer.js, src/components/MediatedRequestsActivities/components/RequestInformation/RequestInformation.js, src/components/MediatedRequestsActivities/components/RequesterInformation/RequesterInformation.js
Reduced console errors
https://folio-org.atlassian.net/browse/UIREQMED-103
=> UIREQMED-103: Fix console errors

CHANGELOG.md
Update changelog after release
https://folio-org.atlassian.net/browse/UIREQMED-105
=> UIREQMED-105: Update changelog after release
